kind: pipeline
type: docker
name: default

steps:
- name: build
  image: ingot
  pull: never
  commands:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
  - make -j$(nproc)
- name: test
  image: ingot
  pull: never
  commands:
  - cd build
  - ctest --verbose
